clear all; 
close all;

% load in each layer data from python script
load('CFin.mat');
load('CFhidden1_AL.mat');
load('CFhidden1_ML.mat');
load('CFhidden2_AL.mat');
load('CFhidden2_ML.mat');
load('CFhidden3_AL.mat');
load('CFhidden3_ML.mat');
load('CFhidden4_AL.mat');
load('CFhidden4_ML.mat');
load('CFout.mat');
load('CDFin.mat');
load('CDFhidden1_AL.mat');
load('CDFhidden1_ML.mat');
load('CDFhidden2_AL.mat');
load('CDFhidden2_ML.mat');
load('CDFhidden3_AL.mat');
load('CDFhidden3_ML.mat');
load('CDFhidden4_AL.mat');
load('CDFhidden4_ML.mat');
load('CDFout.mat');
load('Datain.mat');
load('Datahidden1_AL.mat');
load('Datahidden1_ML.mat');
load('Datahidden2_AL.mat');
load('Datahidden2_ML.mat');
load('Datahidden3_AL.mat');
load('Datahidden3_ML.mat');
load('Datahidden4_AL.mat');
load('Datahidden4_ML.mat');
load('Dataout.mat');

fs = 20;
lw = 2;
ms = 5;

min_input_data      = min(min(Datain));
min_hidden_data1_AL = min(min(Datahidden1_AL));
min_hidden_data1_ML = min(min(Datahidden1_ML));
min_hidden_data2_AL = min(min(Datahidden2_AL));
min_hidden_data2_ML = min(min(Datahidden2_ML));
min_hidden_data3_AL = min(min(Datahidden3_AL));
min_hidden_data3_ML = min(min(Datahidden3_ML));
min_hidden_data4_AL = min(min(Datahidden4_AL));
min_hidden_data4_ML = min(min(Datahidden4_ML));
min_output_data     = min(min(Dataout));
max_input_data      = max(max(Datain));
max_hidden_data1_AL = max(max(Datahidden1_AL));
max_hidden_data1_ML = max(max(Datahidden1_ML));
max_hidden_data2_AL = max(max(Datahidden2_AL));
max_hidden_data2_ML = max(max(Datahidden2_ML));
max_hidden_data3_AL = max(max(Datahidden3_AL));
max_hidden_data3_ML = max(max(Datahidden3_ML));
max_hidden_data4_AL = max(max(Datahidden4_AL));
max_hidden_data4_ML = max(max(Datahidden4_ML));
max_output_data     = max(max(Dataout));
CDFgrid_input       = linspace(min_input_data,      max_input_data,      100);
CDFgrid_hidden1_AL  = linspace(min_hidden_data1_AL, max_hidden_data1_AL, 100);
CDFgrid_hidden1_ML  = linspace(min_hidden_data1_ML, max_hidden_data1_ML, 100);
CDFgrid_hidden2_AL  = linspace(min_hidden_data2_AL, max_hidden_data2_AL, 100);
CDFgrid_hidden2_ML  = linspace(min_hidden_data2_ML, max_hidden_data2_ML, 100);
CDFgrid_hidden3_AL  = linspace(min_hidden_data3_AL, max_hidden_data3_AL, 100);
CDFgrid_hidden3_ML  = linspace(min_hidden_data3_ML, max_hidden_data3_ML, 100);
CDFgrid_hidden4_AL  = linspace(min_hidden_data4_AL, max_hidden_data4_AL, 100);
CDFgrid_hidden4_ML  = linspace(min_hidden_data4_ML, max_hidden_data4_ML, 100);
CDFgrid_output      = linspace(min_output_data,     max_output_data,     100);

figure(1);
subplot(2,6,[1,7]); hold on; grid on;
set(gca,'FontSize',fs);
box on;
h1a = cdfplot(Datain(1,:));
h1b = cdfplot(Datain(2,:));
h1a.Color = 'k'; h1a.LineWidth = lw;
h1b.Color = 'b'; h1b.LineWidth = lw;
plot(CDFgrid_input, CDFin(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_input, CDFin(2,:), 'ob', 'MarkerSize', ms);

subplot(2,6,2); hold on; grid on;
set(gca,'FontSize',fs);
box on;
h2a = cdfplot(Datahidden1_AL(1,:));
h2b = cdfplot(Datahidden1_AL(2,:));
h2c = cdfplot(Datahidden1_AL(3,:));
h2a.Color = 'k'; h2a.LineWidth = lw;
h2b.Color = 'b'; h2b.LineWidth = lw;
h2c.Color = 'r'; h2c.LineWidth = lw;
plot(CDFgrid_hidden1_AL, CDFhidden1_AL(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_hidden1_AL, CDFhidden1_AL(2,:), 'ob', 'MarkerSize', ms);
plot(CDFgrid_hidden1_AL, CDFhidden1_AL(3,:), 'or', 'MarkerSize', ms);

subplot(2,6,8); hold on; grid on;
box on;
set(gca,'FontSize',fs);
h2d = cdfplot(Datahidden1_ML(1,:));
h2e = cdfplot(Datahidden1_ML(2,:));
h2f = cdfplot(Datahidden1_ML(3,:));
h2d.Color = 'k'; h2d.LineWidth = lw;
h2e.Color = 'b'; h2e.LineWidth = lw;
h2f.Color = 'r'; h2f.LineWidth = lw;
plot(CDFgrid_hidden1_ML, CDFhidden1_ML(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_hidden1_ML, CDFhidden1_ML(2,:), 'ob', 'MarkerSize', ms);
plot(CDFgrid_hidden1_ML, CDFhidden1_ML(3,:), 'or', 'MarkerSize', ms);

subplot(2,6,3); hold on; grid on;
box on;
set(gca,'FontSize',fs);
h3a = cdfplot(Datahidden2_AL(1,:));
h3b = cdfplot(Datahidden2_AL(2,:));
h3c = cdfplot(Datahidden2_AL(3,:));
h3a.Color = 'k'; h3a.LineWidth = lw;
h3b.Color = 'b'; h3b.LineWidth = lw;
h3c.Color = 'r'; h3c.LineWidth = lw;
plot(CDFgrid_hidden2_AL, CDFhidden2_AL(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_hidden2_AL, CDFhidden2_AL(2,:), 'ob', 'MarkerSize', ms);
plot(CDFgrid_hidden2_AL, CDFhidden2_AL(3,:), 'or', 'MarkerSize', ms);

subplot(2,6,9); hold on; grid on;
box on;
set(gca,'FontSize',fs);
h3d = cdfplot(Datahidden2_ML(1,:));
h3e = cdfplot(Datahidden2_ML(2,:));
h3f = cdfplot(Datahidden2_ML(3,:));
h3d.Color = 'k'; h3d.LineWidth = lw;
h3e.Color = 'b'; h3e.LineWidth = lw;
h3f.Color = 'r'; h3f.LineWidth = lw;
plot(CDFgrid_hidden2_ML, CDFhidden2_ML(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_hidden2_ML, CDFhidden2_ML(2,:), 'ob', 'MarkerSize', ms);
plot(CDFgrid_hidden2_ML, CDFhidden2_ML(3,:), 'or', 'MarkerSize', ms);

subplot(2,6,4); hold on; grid on;
box on;
set(gca,'FontSize',fs);
h4a = cdfplot(Datahidden3_AL(1,:));
h4b = cdfplot(Datahidden3_AL(2,:));
h4c = cdfplot(Datahidden3_AL(3,:));
h4a.Color = 'k'; h4a.LineWidth = lw;
h4b.Color = 'b'; h4b.LineWidth = lw;
h4c.Color = 'r'; h4c.LineWidth = lw;
plot(CDFgrid_hidden3_AL, CDFhidden3_AL(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_hidden3_AL, CDFhidden3_AL(2,:), 'ob', 'MarkerSize', ms);
plot(CDFgrid_hidden3_AL, CDFhidden3_AL(3,:), 'or', 'MarkerSize', ms);

subplot(2,6,10); hold on; grid on;
box on;
set(gca,'FontSize',fs);
h4d = cdfplot(Datahidden3_ML(1,:));
h4e = cdfplot(Datahidden3_ML(2,:));
h4f = cdfplot(Datahidden3_ML(3,:));
h4d.Color = 'k'; h4d.LineWidth = lw;
h4e.Color = 'b'; h4e.LineWidth = lw;
h4f.Color = 'r'; h4f.LineWidth = lw;
plot(CDFgrid_hidden3_ML, CDFhidden3_ML(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_hidden3_ML, CDFhidden3_ML(2,:), 'ob', 'MarkerSize', ms);
plot(CDFgrid_hidden3_ML, CDFhidden3_ML(3,:), 'or', 'MarkerSize', ms);

subplot(2,6,5); hold on; grid on;
box on;
set(gca,'FontSize',fs);
h5a = cdfplot(Datahidden4_AL(1,:));
h5b = cdfplot(Datahidden4_AL(2,:));
h5c = cdfplot(Datahidden4_AL(3,:));
h5a.Color = 'k'; h5a.LineWidth = lw;
h5b.Color = 'b'; h5b.LineWidth = lw;
h5c.Color = 'r'; h5c.LineWidth = lw;
plot(CDFgrid_hidden4_AL, CDFhidden4_AL(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_hidden4_AL, CDFhidden4_AL(2,:), 'ob', 'MarkerSize', ms);
plot(CDFgrid_hidden4_AL, CDFhidden4_AL(3,:), 'or', 'MarkerSize', ms);

subplot(2,6,11); hold on; grid on;
box on;
set(gca,'FontSize',fs);
h5d = cdfplot(Datahidden4_ML(1,:));
h5e = cdfplot(Datahidden4_ML(2,:));
h5f = cdfplot(Datahidden4_ML(3,:));
h5d.Color = 'k'; h5d.LineWidth = lw;
h5e.Color = 'b'; h5e.LineWidth = lw;
h5f.Color = 'r'; h5f.LineWidth = lw;
plot(CDFgrid_hidden4_ML, CDFhidden4_ML(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_hidden4_ML, CDFhidden4_ML(2,:), 'ob', 'MarkerSize', ms);
plot(CDFgrid_hidden4_ML, CDFhidden4_ML(3,:), 'or', 'MarkerSize', ms);

subplot(2,6,[6,12]); hold on; grid on;
box on;
set(gca,'FontSize',fs);
h6a = cdfplot(Dataout(1,:));
h6b = cdfplot(Dataout(2,:));
h6a.Color = 'k'; h6a.LineWidth = lw;
h6b.Color = 'b'; h6b.LineWidth = lw;
plot(CDFgrid_output, CDFout(1,:), 'ok', 'MarkerSize', ms);
plot(CDFgrid_output, CDFout(2,:), 'ob', 'MarkerSize', ms);

delete(findall(findall(gcf,'Type','axe'),'Type','text'))

subplot(2,6,[1,7]); hold on; grid on;
ylabel('$\Phi_{0}$','Interpreter','latex','FontSize', fs);
xlabel('$x$','Interpreter','latex','FontSize',fs);
subplot(2,6,2); hold on; grid on;
ylabel('$\Phi^{-}_{1}$','Interpreter','latex','FontSize',fs);
xlim([-5, 5]);
subplot(2,6,8); hold on; grid on;
ylabel('$\Phi^{+}_{1}$','Interpreter','latex','FontSize',fs);
xlabel('$x$','Interpreter','latex','FontSize',fs);
xlim([0, 5]);
subplot(2,6,3); hold on; grid on;
ylabel('$\Phi^{-}_{2}$','Interpreter','latex','FontSize',fs);
xlim([-5, 5]);
subplot(2,6,9); hold on; grid on;
ylabel('$\Phi^{+}_{2}$','Interpreter','latex','FontSize',fs);
xlabel('$x$','Interpreter','latex','FontSize',fs);
xlim([0, 5]);
subplot(2,6,4); hold on; grid on;
ylabel('$\Phi^{-}_{3}$','Interpreter','latex','FontSize',fs);
xlim([-5, 6]);
subplot(2,6,10); hold on; grid on;
ylabel('$\Phi^{+}_{3}$','Interpreter','latex','FontSize',fs);
xlabel('$x$','Interpreter','latex','FontSize',fs);
xlim([0, 6]);
subplot(2,6,5); hold on; grid on;
ylabel('$\Phi^{-}_{4}$','Interpreter','latex','FontSize',fs);
xlim([-6, 5]);
subplot(2,6,11); hold on; grid on;
ylabel('$\Phi^{+}_{4}$','Interpreter','latex','FontSize',fs);
xlabel('$x$','Interpreter','latex','FontSize',fs);
xlim([0, 4]);
subplot(2,6,[6,12]); hold on; grid on;
ylabel('$\Phi_{5}$','Interpreter','latex','FontSize', fs);
xlabel('$x$','Interpreter','latex','FontSize',fs);
xlim([-6, 6]);


